# Generated by Django 3.2 on 2021-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userfile_uploaded_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
    ]
