# Generated by Django 3.2 on 2021-04-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210412_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='in_trash',
            field=models.BooleanField(default=0),
        ),
    ]
